### ISSUE TITLE
Cannot read DSR map HKX files

### ISSUE THREAD

**Issue by dark-souls-playground** [JKAnderson/SoulsFormats#11]
Firstly, thanks for this awesome set of tools! I'm using this with Dark Souls Remastered. I know that some file formats have changed between DS1 and DSR, but I'm only focusing on map models.

I can successfully load character models and map piece models, but I'm having trouble loading map collision models. Here's what I'm trying:

Logic:
```
string ROOT_INPUT_FOLDER = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\DARK SOULS REMASTERED\\";
string inputBhdFile = ROOT_INPUT_FOLDER + "map\\m10_02_00_00\\h10_02_00_00.hkxbhd";
string inputBdtFile = ROOT_INPUT_FOLDER + "map\\m10_02_00_00\\h10_02_00_00.hkxbdt";
BXF3 bxf = BXF3.Read(inputBhdFile, inputBdtFile); // this works
BinderFile file = bxf.Files[0]; // file.Name is "m10_02_00_00\\h0000B2A10.hkx.dcx"
byte[] bytes = DCX.Decompress(file.Bytes); // this works
SoulsFormats.HKX hkx = SoulsFormats.HKX.Read(bytes, HKX.HKXVariation.HKXDS1); // this throws InvalidDataException
```

Output Exception message:
`Read UInt32: 0xAC230300 | Expected: 0x57E0E057 | Ending position: 0x4`

**Comment by JKAnderson** [comment]
This library does not include any Havok support. You are using someone else's fork and should submit your issue there instead.

**Comment by dark-souls-playground** [comment]
Ah, I'm sorry, you're right, I was using DSMapStudio, which includes a fork of this. Their project included two separate HKX readers, one in a separate namespace, and one in the SoulsFormats namespace, so I was hoping and assuming that the one in the SoulsFormats namespace was an official one.

Thanks for clarifying and for the quick reply!
