### ISSUE TITLE
Elden Ring support

### ISSUE THREAD

**Issue by picklejar76** [JKAnderson/SoulsFormats#12]
Any plans to add support for Elden Ring? At minimum, maybe just add comments in the README and FORMATS. For example, "some formats appear to be the same as DS3, but not planning to enhance this anytime soon." ?

**Comment by AaronWebster** [comment]
Watch activity on [this branch.](https://github.com/JKAnderson/SoulsFormats/tree/er)

**Comment by picklejar76** [comment]
Thanks!
