### ISSUE TITLE
MDO Format listed for KF1 is actually from Sword of Moonlight

### ISSUE THREAD

**Issue by TheStolenBattenberg** [JKAnderson/SoulsFormats#5]
KF1 doesn't use this file format, it's from the Sword of Moonlight King's Field maker tool which was used to remake KF1 by FromSoft themselves.

I know King's Field formats aren't your primary target, but a few rough specs for them are in my repository 'Psycpros'. Most of the formats are either just standard PsyQ formats or modified variants, like .MIM and .MO which use 'MIMe' routines.

Sorry for being a pain :)

**Comment by JKAnderson** [comment]
You are correct, thank you.
