### ISSUE TITLE
System.IO.InvalidDataException:“Read ASCII: ?:? | Expected ASCII: BDF4” 

### ISSUE THREAD

**Issue by miccall** [JKAnderson/SoulsFormats#6]
I will export the models from “Sekiro”：
The folder ：
![image](https://user-images.githubusercontent.com/20721387/75968486-707f7600-5f08-11ea-9744-9750a21448ca.png)
I have run this code 
``` c#
BXF4 bxf = BXF4.Read(@"E:\Sekiro\data2.bhd", @"E:\Sekiro\data2.bdt");
```

Its give me Exception : 
![image](https://user-images.githubusercontent.com/20721387/75968647-bc321f80-5f08-11ea-8d96-a4e063e79cfc.png)

How can I fix that?

**Comment by JKAnderson** [comment]
The Data bhds/bdts are a different format from typical BXFs, and the bhd is also encrypted.  
Extracting them is more complicated too so I recommend you just use [UXM](https://github.com/JKAnderson/UXM/releases/tag/2.4) instead.  
If you do need to do it yourself for whatever reason you'll need to use the BHD5 class after decryption; [this class](https://github.com/JKAnderson/UXM/blob/master/UXM/ArchiveUnpacker.cs) handles most of that in UXM.
